"""Configuration for the FanOutAgent pattern."""

from collections.abc import Callable
from dataclasses import dataclass
from typing import Any

from google.adk.agents import BaseAgent


@dataclass
class FanOutConfig:
    """All-in-one configuration for fan-out parallel work distribution.

    Callbacks contract
    ------------------
    prepare_work_items(state) -> list[Any]
        Reads from session state, returns list of work items (each item is
        opaque to the base). Returns ``[]`` for early exit.

    create_agent(index, work_item, output_key) -> LlmAgent
        Factory that returns a fully configured ``LlmAgent``. The
        ``output_key`` is generated by the base (``{agent_name}_item_{i}``)
        so the base knows where to collect results.

    aggregate(outputs: list[dict]) -> Any
        Receives list of normalized dicts (pydantic models already
        ``.model_dump()``'d). Returns value to write to
        ``state[output_key]``. Default: concatenates all
        ``output[results_field]`` lists into ``{results_field: all_items}``.
    """

    # === Required Fields ===
    prepare_work_items: Callable[[dict[str, Any]], list[Any]]
    create_agent: Callable[[int, Any, str], BaseAgent]
    output_key: str

    # === Optional Fields ===
    aggregate: Callable[[list[dict]], Any] | None = None
    results_field: str = "findings"
    empty_message: str | None = None
