"""add_name_to_jobs

Revision ID: 1333a39d8e09
Revises: 063e0da43d5f
Create Date: 2026-01-25 17:19:16.070005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1333a39d8e09'
down_revision: Union[str, Sequence[str], None] = '063e0da43d5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('name', sa.String(), nullable=False, server_default="Audit"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'name')
    # ### end Alembic commands ###
